### ISSUE TITLE
Problem with recent versions of Python

### ISSUE THREAD

**Issue by sguarin** [omniti-labs/pg_extractor#53]
When running on recent versions of Python we got buffer attribute does not exist on sys.stdout.

```
$ python3.8 ~/usr/pg_extractor/pg_extractor.py --getall --getsequence --orreplace --hostname . --host dbhost --dbname dbname
Creating temp dump file...
Extracting tables...
Extracting functions & aggregates...
Extracting sequences...
Traceback (most recent call last):
  File "/home/sguarin/usr/pg_extractor/pg_extractor.py", line 1500, in <module>
    p.or_replace()
  File "/home/sguarin/usr/pg_extractor/pg_extractor.py", line 797, in or_replace
    sys.stdout.buffer.write(
AttributeError: '_io.BufferedWriter' object has no attribute 'buffer'
```

When running the same on python 3.4 all runs succesfully.

**Comment by sguarin** [comment]
With this [commit](https://github.com/sguarin/pg_extractor/commit/4df0a5e21d62a88941a29fe762b133d5425bd43d) works for me, but stop working with Python 3.4.

**Comment by keithf4** [comment]
Are you using any customized libraries for python? I've been using Python 3.6 myself with pg_extractor for quite a while without any issues. I see you're using 3.8, so I installed and tested with that without any issues as well
```
$ python3.8 ~/Projects/pg_extractor/pg_extractor.py --getall
Creating temp dump file...
Extracting tables...
Extracting remaining objects...
Done
```
Looking through the documentation, the buffer attribute is mentioned as being available through 3.9 in a note found at the bottom of the sys.std* section of the docs - https://docs.python.org/3.8/library/sys.html?highlight=stdout#sys.stdout

The last paragraph in that note mentions the use of custom some python write libraries not making the `buffer` attribute available.

**Comment by keithf4** [comment]
Ran with your specific options given as well without any issues
```
$ python3.8 ~/Projects/pg_extractor/pg_extractor.py --getall --getsequence --orreplace --hostname . --host localhost --dbname keith
Creating temp dump file...
Extracting tables...
Extracting sequences...
Extracting remaining objects...
Done
```

**Comment by keithf4** [comment]
Closing this issue for now. If you still continue to have this issue and need assistance, feel free to re-open, but this does seem to be related to a custom library somewhere in your environment.

**Comment by xvaara** [comment]
I had the same problem with fresh ubuntu python 3.9.5 and on my mac with 3.9 and 3.10... 3.7 seemed to work on the mac.
